Add rworkflows
scverse/anndataR pull request #105
Opened 2023-09-18 12:48 UTC by bschilder

# anndataR 0.99.0

## New features

- Add `rworkflows` CI.
- Update *lint.yaml* to use `actions/checkout@v4` (which has less issues).
- New function `setup_conda` automatically installs miniconda 
  and sets up conda env: #97
- Change version to Bioc-recommended devel version: 0.99.0

2023-09-18 14:36 UTC, rcannood requested changes

2023-09-18 14:36 UTC, rcannood commented on .github/workflows/pkgdown.yaml
I think it's better to revert this change, because the site is being pushed to a different repository.

2023-09-18 14:36 UTC, rcannood commented on NEWS.md
> +
Version 0.1.0 hasn't been released yet, so we can just set the version to `0.99.0`. No need to add the "new features" to the changelog then, imo.

```suggestion
```

2023-09-18 14:36 UTC, rcannood commented on R/setup_conda.R
> +#' @export
I wouldn't export this function for now, at least until there is a reticulate backend. Also, we shouldn't create an Rd file for functions that aren't exported.

```suggestion
#' @noRd
```

2023-09-18 14:36 UTC, rcannood commented on man/setup_conda.Rd
This should be removed (see earlier comment)

2023-09-18 14:36 UTC, rcannood commented on .github/workflows/R-CMD-check.yaml
> -        shell: Rscript {0}
Will `neurogenomics/rworkflows@master` also install these packages?

2023-09-19 07:16 UTC, bschilder commented on NEWS.md
> +
Ok, I'll make the previous version 0.99.0 and my current version 0.99.1 to make the distinction that these were done separately.

2023-09-19 07:16 UTC, bschilder commented on .github/workflows/pkgdown.yaml
Agreed! Though I'll also look into making rworkflows a bit more flexible for this use case.

2023-09-19 07:41 UTC, bschilder commented on .github/workflows/R-CMD-check.yaml
> -        shell: Rscript {0}
Just to log our in-person discussion here, we talked about strategies for installing `miniconda`/`anndata`/`scanpy`. 

Here are some of the proposed options:
1. Trigger the `setup_conda` function whenever a `AnnDataR` function that requires `miniconda`/`anndata`/`scanpy` is used. We use this strategy for non-R dependencies in [`MAGMA.Celltyping`](https://github.com/neurogenomics/MAGMA_Celltyping), which requires the command line tool `MAGMA` for certain functions. The goal in that case is to remove any manual setup steps for the user. However, in the case of GHA, the only place that this would currently be triggered within `AnnDataR` is the unit tests, which @rcannood was opposed to. From a philosophical standpoint I have less of an issue with additional installs being triggered post-`AnnDataR` installation, but I do have some practical concerns that R might have some trouble using the `reticulate` conda env  right after it's been created. For this reason `basilisk` might be a better option, which switches between envs much more smoothly.
2. Add an optional step to rworkflows action to setup a conda env (I've actually been meaning to add this feature since its inception). Might be the best option tho, and shouldn't be too hard to implement (famous last words) 
3. On GHA, skip any tests that require `miniconda`/`anndata`/`scanpy`. Not a very good option, since it creates a huge blindspot during testing.

2023-09-20 10:19 UTC, rcannood commented
Can you merge the main branch into this PR?

2023-11-29 12:53 UTC, bschilder commented
> This PR contains a lot of changes which are not relevant to the rworkflows CI. I feel like this PR should only make changes to the .github folder (and maybe the README or the DESCRIPTION).

I was a bit too optimistic about my other PR and thought that would become "main" quite soon. Seems like those changes are going to take a while to break up and review, so i can change this PR back.

2024-06-27 21:00 UTC, rcannood commented
Closing this PR for now

2024-06-27 21:00 UTC, closed without merging