Add writing compressed h5ad files
scverse/anndataR pull request #108
Opened 2023-09-18 14:39 UTC by LouiseDck

2023-09-19 14:28 UTC, ivirshup commented on R/write_h5ad_helpers.R
> +  hdf5_write_compressed(file, paste0(name, "/codes"), as.integer(value), compression)
Do you still need the -1 here?

2023-11-30 18:25 UTC, rcannood requested changes
Woop woop! :partying_face: 

I made some minor suggestions -- WDYT @LouiseDck ?

About halfway through the review I started regretting not simply creating a PR with my proposed changes rather than all of these suggestions ...

2023-11-30 18:25 UTC, rcannood commented on R/HDF5AnnData.R
> +to_HDF5AnnData <- function(adata, file, ...) { # nolint
See above

```suggestion
to_HDF5AnnData <- function(adata, file, compression = c("none", "gzip", "lzf")) { # nolint
```

2023-11-30 18:25 UTC, rcannood commented on R/HDF5AnnData.R
> +    ...
See above

```suggestion
    compression = compression
```

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad.R
> +#' @param ... Extra arguments will be passed to the appropriate convertor
See above

```suggestion
  #' @param compression The compression algorithm to use when writing the
  #'  HDF5 file. Can be one of `"none"`, `"gzip"` or `"lzf"`. Defaults to
  #' `"none"`.
```

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad.R
> +write_h5ad <- function(object, path, ...) {
See above

```suggestion
write_h5ad <- function(object, path, compression = c("none", "gzip", "lzf")) {
```

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad.R
> +      ...
See above
```suggestion
      compression = compression
```

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad.R
> +      ...
See above
```suggestion
      compression = compression
```

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad.R
> +    to_HDF5AnnData(object, path, ...)
See above
```suggestion
    to_HDF5AnnData(object, path, compression = compression)
```

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad_helpers.R
> +#' one of `"NONE"`, `"GZIP"` or `"LZF"`. Defaults to `"NONE"`.
See above

```suggestion
#' one of `"none"`, `"gzip"` or `"lzf"`. Defaults to `"none"`.
```

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad_helpers.R
> +  compression <- match.arg(compression, choices = c("GZIP", "LZF", "NONE"))
See above.

```suggestion
write_h5ad_element <- function(value, file, name, compression = c("none", "gzip", "lzf"), ...) { # nolint
  compression <- match.arg(compression)

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad_helpers.R
> +#' one of `"NONE"`, `"GZIP"` or `"LZF"`.
See above

```suggestion
#' one of `"none"`, `"gzip"` or `"lzf"`. Defaults to `"none"`.
```

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad_helpers.R
> +#' `"NONE"`, `"GZIP"` or `"LZF"`.
See above

```suggestion
#' @param compression The compression to use when writing the element. Can be
#' one of `"none"`, `"gzip"` or `"lzf"`. Defaults to `"none"`.
```

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad_helpers.R
> +#' `"NONE"`, `"GZIP"` or `"LZF"`.
See above

```suggestion
#' @param compression The compression to use when writing the element. Can be
#' one of `"none"`, `"gzip"` or `"lzf"`. Defaults to `"none"`.
```

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad_helpers.R
> +#' `"NONE"`, `"GZIP"` or `"LZF"`.
See above

```suggestion
#' @param compression The compression to use when writing the element. Can be
#' one of `"none"`, `"gzip"` or `"lzf"`. Defaults to `"none"`.
```

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad_helpers.R
> +#' `"NONE"`, `"GZIP"` or `"LZF"`.
See above

```suggestion
#' @param compression The compression to use when writing the element. Can be
#' one of `"none"`, `"gzip"` or `"lzf"`. Defaults to `"none"`.
```

2023-11-30 18:25 UTC, rcannood commented on R/write_h5ad_helpers.R
> +#' `"NONE"`, `"GZIP"` or `"LZF"`.
See above

```suggestion
#' @param compression The compression to use when writing the element. Can be
#' one of `"none"`, `"gzip"` or `"lzf"`. Defaults to `"none"`.
```

2023-11-30 18:25 UTC, rcannood commented on tests/testthat/test-HDF5-write.R
> +  expect_silent(write_h5ad_element(array, h5ad_file, "dense_array", compression = "NONE"))
```suggestion
  expect_silent(write_h5ad_element(array, h5ad_file, "dense_array", compression = "none"))

2023-11-30 18:25 UTC, rcannood commented on tests/testthat/test-HDF5-write.R
> +  expect_silent(write_h5ad_element(csc_array, h5ad_file, "csc_array", compression = "NONE"))
```suggestion
  expect_silent(write_h5ad_element(csc_array, h5ad_file, "csc_array", compression = "none"))

2023-11-30 18:25 UTC, rcannood commented on tests/testthat/test-HDF5-write.R
> +  expect_silent(write_h5ad_element(csr_array, h5ad_file, "csr_array", compression = "NONE"))
```suggestion
  expect_silent(write_h5ad_element(csr_array, h5ad_file, "csr_array", compression = "none"))

2023-11-30 18:25 UTC, rcannood commented on tests/testthat/test-HDF5-write.R
> +  expect_silent(write_h5ad_element(mapping, h5ad_file, "mapping", compression = "NONE"))
```suggestion
  expect_silent(write_h5ad_element(mapping, h5ad_file, "mapping", compression = "NONE"))
```

2023-11-30 18:25 UTC, rcannood commented on tests/testthat/test-HDF5-write.R
> +  write_h5ad(adata, h5ad_file_gzip, compression = "GZIP")
```suggestion
  write_h5ad(adata, h5ad_file_none, compression = "none")
  write_h5ad(adata, h5ad_file_gzip, compression = "gzip")
```

2023-11-30 18:25 UTC, rcannood commented on tests/testthat/test-HDF5-write.R
> +  write_h5ad(adata, h5ad_file_lzf, compression = "LZF")
```suggestion
  write_h5ad(adata, h5ad_file_none, compression = "none")
  write_h5ad(adata, h5ad_file_lzf, compression = "lzf")

2023-12-01 21:11 UTC, rcannood approved these changes

2023-12-01 21:11 UTC, merged