wip new seurat conversion
scverse/anndataR pull request #183
Opened 2024-09-19 20:58 UTC by rcannood

2024-10-18 09:13 UTC, rcannood commented
Note: Could use https://satijalab.github.io/seurat-object/reference/UpdateSeuratObject.html to update a Seurat <v5 object to v5 in `from_Seurat()`.

2024-11-06 08:44 UTC, lazappi requested changes
I made a bunch of comments, most of them are fairly minor. I haven't tried running anything yet though so possible I missed things.

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +      stop("each graph must be a character vector of length 1")
Maybe this is clearer:

```suggestion
      stop("item ", graph_name, "in graph_mapping is not a character vector of length 1")
```

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +  obj@misc <- list()
Can probably also avoid the `@` here

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +    misc_data <- adata[[misc[[1]]]]
Is it possible to get the names without getting everything in the slot? Just because for `H5ADAnnData` this will drag everything in that slot into memory (I think).

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +    if (!misc[[1]] %in% expected_slots) {
The code would be a bit easier to follow if there was something like:

```r
misc_slot <- misc[[1]]
misc_key <- misc[[2]]
```

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +  }
These could have different messages to make it clearer what the problem is.

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +  }
Do you need to do this or can you assume there will always be a name? It might depend what the guessing function do which I haven't looked at yet.

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +  }
I think other missing things are an error rather than a warning?

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +  do.call(SeuratObject::CreateDimReducObject, args)
Is there a reason to do it this way rather than just calling the function with arguments?

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +  }
Ah, I guess you use `NULL` to mean `adata$X` rather than `adata$layers["X"]`. I missed that before.

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
>  #' to_Seurat(ad)
It would be nice to have some examples showing how the mapping works.

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +#' * All Seurat layers are copied by name.
I assume to `adata$layers` and `adata$X` is empty?

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +#' Example: `obsm_mapping = list(pca = list(key = "PC_", obsm = "X_pca", varm = "PCs"))`.
I'll see below but it should probably be possible for some of these to be missing

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +#' A named list to map Seurat PCA loadings to AnnData `varm`.
Is `obsm_mapping` also copying things to `varm`? Do we need both?

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +#' * The name of the PCA loadings is copied by name.
Only PCA or any other reduction that has loadings?

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +#' @section Obsp mapping:
I would not capitalise obsp and maybe format it as code

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +#' * No data is mapped to `varp`.
This bit I don't understand. Why have a first element if it's always the same and what does the third element do?

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
>  from_Seurat <- function(
Maybe these functions should be called something like `anndata_from_seurat()` just to make it a bit clearer?

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +    assay_name = "RNA",
This could be the name of the first assay by default in case it's something else

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> +  }
I think this is checking two things. I would probably have one check for the object version (with a prompt to upgrade it) and a second check later for the assay name.

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
> -    }
I think this is nicer behaviour, I would put this back

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
>    obs <- seurat_obj@meta.data
I'm pretty sure `seurat_obj[[]]` will get this but would need to double check

2024-11-06 08:44 UTC, lazappi commented on R/Seurat.R
>    )
Maybe it's better to wait until the end of the function to create this? Otherwise you could end up with incomplete files for `H5ADAnnData`.

2024-11-06 17:16 UTC, LouiseDck requested changes

2024-11-06 17:16 UTC, LouiseDck commented on R/Seurat.R
> +    }
I don't mind this control flow

2024-11-06 17:16 UTC, LouiseDck commented on R/Seurat.R
>      }
Lots of checking, but it is still possible that not all elements of the list are named. If e.g. only one of the elements is named, the unnamed reductions get mapped to an "X" reduction in Seurat, and overwrite each other.

2024-11-06 17:16 UTC, LouiseDck commented on R/Seurat.R
> +          !all(c("key", "obsm", "varm") %in% names(reduction))
I have an issue with requiring the "varm" name in the list: for many dimensionality reductions you do not get loadings in "varm", so requiring it seems a bit harsh?

2024-11-06 17:16 UTC, LouiseDck commented on R/Seurat.R
> +  obj@misc <- list()
Out of curiosity, why do you want to avoid the `@`?

2024-11-06 17:16 UTC, LouiseDck commented on R/Seurat.R
> +#' * All Seurat layers are copied by name.
I want it emphasized that this means that by default, `adata$X` will be `NULL`, and that if you want to prevent this you should prevent a mapping.

2024-11-06 17:16 UTC, LouiseDck commented on R/Seurat.R
> +#' corresponding slot. The third element is used to subset the data even further.
Maybe this is my inexperience with Seurat showing, but what do you mean by `used to subset the data further`?

2024-11-06 17:16 UTC, LouiseDck commented on R/Seurat.R
>  from_Seurat <- function(
I disagree, as we only aim to convert from & to anndata.
However, if we want to emphasize this, I would prefer `anndata_to_seurat()` and `seurat_to_anndata()`

2024-11-06 17:16 UTC, LouiseDck commented on R/Seurat.R
> -    }
I agree, if you want to pick a default assay to convert it should not be `RNA` by default, but the `DefaultAssay`

2024-11-06 17:16 UTC, LouiseDck commented on R/Seurat.R
> +  }
I might overlook this, but there's no need to specifiy "varm" in the mapping, right? In that case, I think the documentation of the function needs an update.

2024-11-06 17:16 UTC, LouiseDck commented on DESCRIPTION
> -    BiocStyle,
cf #169 but we should indeed discuss this

2024-11-06 19:06 UTC, rcannood commented on DESCRIPTION
> -    BiocStyle,
Removed changes that were not related to Seurat and moved the discussion to #191 !

2024-11-06 19:10 UTC, rcannood commented on R/Seurat.R
> +#'   "Miscellaneous mapping" for more details.
At the moment I named the arguments based on what the object that ends up being created. In `to_Seurat` we're deciding on what needs to be copied into the Seurat object, which is why the argument names are named after seurat object slots.

2024-11-06 19:12 UTC, rcannood commented on R/Seurat.R
> +#' Example: `layer_mapping = list(counts = "counts", data = NULL, foo = "bar")`.
Fixed!

2024-11-06 19:14 UTC, rcannood commented on R/Seurat.R
> +#' If `NULL`, the internal function `to_Seurat_guess_layers` will be used to guess the layer mapping as follows:
Originally each of the functions were being exported but this resulted in a lot of clutter in the package documentation, which is why they are currently internal functions. Would you prefer to export them?

2024-11-06 19:23 UTC, rcannood commented on R/Seurat.R
> +#' A named list to map AnnData `obsm` and `varm` to Seurat reductions. Each item in the list must be a named list
Hmm. Or what about "AnnData `$obsm` and `$varm`"?

2024-11-06 19:24 UTC, rcannood commented on R/Seurat.R
> +#' character vector of length 1.
Fixed!

2024-11-06 19:25 UTC, rcannood commented on R/Seurat.R
> +#' a named list with one or two elements. The first element must be one of: 'X', 'layers', 'obs', 'obsm', 'obsp', 'var',
Fixed!

2024-11-06 19:25 UTC, rcannood commented on R/Seurat.R
> +#' not present, the data in the first element will be used.
I tried to clarify -- is this better?

2024-11-06 19:31 UTC, rcannood commented on R/Seurat.R
> +#' * If `adata$uns` is defined, this is mapped to a misc value named `uns`.
:+1:!

2024-11-06 19:41 UTC, rcannood commented on R/Seurat.R
>    requireNamespace("SeuratObject")
:+1:!

2024-11-06 19:52 UTC, rcannood commented on R/Seurat.R
> +  }
I'd say it's okay with using `layer_mapping = c("counts", "data")` as a synonym for `c(counts = "counts", data = "data")`.

2024-11-06 19:55 UTC, rcannood commented on R/Seurat.R
> +    }
I changed 

```r
    if (to == "counts" || to == "data") {
      next
    }
```

to 

```r
    if (!to %in% c("counts", "data")) {
      SeuratObject::LayerData(obj, assay = assay_name, layer = to) <- adata$layers[[from]]
    }
```

2024-11-06 19:56 UTC, rcannood commented on R/Seurat.R
> +    obj@assays[[assay_name]] <- SeuratObject::AddMetaData(
Let me know if you'd prefer something else :relaxed:

2024-11-06 19:59 UTC, rcannood commented on R/Seurat.R
> +  rownames(obj) <- var_names
Maybe. Seurat might have done something with those dimnames by then...

2024-11-06 19:59 UTC, rcannood commented on R/Seurat.R
>      }
:+1:

2024-11-06 20:00 UTC, rcannood commented on R/Seurat.R
> +  obj@misc <- list()
I believe @ is usually used for accessing internal data structures which end users should not be messing around with. 

I'm not sure whether there is always an easy alternative. Let me know if you find one :)

2024-11-06 20:02 UTC, rcannood commented on R/Seurat.R
> +    misc_data <- adata[[misc[[1]]]]
Good point. Probably not, unless we 

```r
if (slot_name == "obs") adata$obs_keys()
elif (slot_name == "var") adata$var_keys()
elif ...
```

2024-11-06 20:04 UTC, rcannood commented on R/Seurat.R
> +    if (!misc[[1]] %in% expected_slots) {
done!

2024-11-06 20:04 UTC, rcannood commented on R/Seurat.R
> +  }
true!

2024-11-06 20:05 UTC, rcannood commented on R/Seurat.R
> +  }
well you need to have some way of allowing the user to use `$X` as the seurat counts of data, so by using `NULL` the `$X` will be used.

2024-11-06 20:08 UTC, rcannood commented on R/Seurat.R
> +  }
True. This was a leftover from when the defaults of to_seurat and from_seurat just had a bunch of defaults without checking whether these exist in the original anndata / seurat object.

2024-11-06 20:13 UTC, rcannood commented on R/Seurat.R
> +  do.call(SeuratObject::CreateDimReducObject, args)
fixed!

2024-11-06 20:13 UTC, rcannood commented on R/Seurat.R
> +  }
:+1:

2024-11-06 20:13 UTC, rcannood commented on R/Seurat.R
>  #' to_Seurat(ad)
true!

2024-11-06 20:14 UTC, rcannood commented on R/Seurat.R
> +#' * All Seurat layers are copied by name.
Yes, I'll clarify.

2024-11-06 20:17 UTC, rcannood commented on R/Seurat.R
> +#' Example: `obsm_mapping = list(pca = list(key = "PC_", obsm = "X_pca", varm = "PCs"))`.
Sorry, the documentation is no longer correct, I'll fix.

2024-11-06 20:20 UTC, rcannood commented on R/Seurat.R
> +#' A named list to map Seurat PCA loadings to AnnData `varm`.
Sorry, the `obsm_mapping` documentation was wrong -- is fixed now.

2024-11-06 20:26 UTC, rcannood commented on R/Seurat.R
> +#' * No data is mapped to `varp`.
Tried to clarify the docs

2024-11-06 20:27 UTC, rcannood commented on R/Seurat.R
>  from_Seurat <- function(
I'd be fine with:

* `anndata_to_seurat` & `seurat_to_anndata`
* `to_seurat` & `from_seurat`
* or keep it as is, namely `to_Seurat` and `from_Seurat`

2024-11-06 20:33 UTC, rcannood commented on R/Seurat.R
> +    assay_name = "RNA",
true -- `obj@active.assay`?

2024-11-06 20:37 UTC, rcannood commented on R/Seurat.R
> +  }
I'll add it to the error message!

2024-11-06 20:41 UTC, rcannood commented on R/Seurat.R
> -    }
Fixed!

2024-11-06 20:59 UTC, rcannood commented on R/Seurat.R
>    )
True. Otoh, it would make the whole operation a whole lot less memory efficient.

I could add a tryCatch which removes the file on error. WDYT?

2024-11-06 20:59 UTC, rcannood commented on R/Seurat.R
> +    key2 <- obsm[[2]]
+1

2024-11-06 21:02 UTC, rcannood commented on R/Seurat.R
>      }
To not make it too complicated, can we assume that reduction_mapping is always a named list?

2024-11-06 21:03 UTC, rcannood commented on R/Seurat.R
> +          !all(c("key", "obsm", "varm") %in% names(reduction))
+1!

2024-11-06 21:03 UTC, rcannood commented on R/Seurat.R
> +#' * All Seurat layers are copied by name.
+1!

2024-11-06 21:04 UTC, rcannood commented on R/Seurat.R
> +#' corresponding slot. The third element is used to subset the data even further.
Phrasing was improved

2024-11-06 21:05 UTC, rcannood commented on R/Seurat.R
> +  }
not sure what you mean -- could you clarify?

2024-11-07 08:45 UTC, lazappi commented on R/Seurat.R
> +#' If `NULL`, the internal function `to_Seurat_guess_layers` will be used to guess the layer mapping as follows:
Not necessarily, pros and cons. But if they were exported then the documentation should go there.

2024-11-07 08:48 UTC, lazappi commented on R/Seurat.R
> +#' A named list to map AnnData `obsm` and `varm` to Seurat reductions. Each item in the list must be a named list
Yeah, maybe. I just think it's easy to get mixed up between different objects/arguments so it helps to be as clear as possible. I don't really mind how exactly, as long as it's consistent.

2024-11-07 08:50 UTC, lazappi commented on R/Seurat.R
> +#' not present, the data in the first element will be used.
Yep, as long as it matches what it does in practice. What it says now is different to what I understood before.

2024-11-07 08:51 UTC, lazappi commented on R/Seurat.R
> +  rownames(obj) <- var_names
Ok. If there is a reason for it then it's fine.

2024-11-07 08:55 UTC, lazappi commented on R/Seurat.R
> +    misc_data <- adata[[misc[[1]]]]
In theory yes (or a case statement might be nicer) but I think at the moment `adata$obs_keys()` etc. read everything anyway so not much point unless those are changed. Maybe don't worry about it for this PR.

2024-11-07 08:58 UTC, lazappi commented on R/Seurat.R
>    )
Maybe, if there's a nice way to do it. The way we write stuff at the moment is a bit risky in general so maybe it's more a design flaw in `H5ADAnnData`...

2024-11-07 09:00 UTC, rcannood commented on R/Seurat.R
> +#' @section Obsp mapping:
Good point, still need to change this

2024-11-07 09:01 UTC, rcannood commented on R/Seurat.R
> +    assay_name = "RNA",
I changed the default to NULL. If set to NULL, `SeuratObject::DefaultAssay(seurat_obj)` will be used.

2024-11-07 09:01 UTC, rcannood commented on R/Seurat.R
>    obs <- seurat_obj@meta.data
Ok, let me know ^^

2024-11-07 10:08 UTC, lazappi requested changes
Mostly adding suggestions for accessing stuff from a Seurat object. I didn't comment on every line but I think there should be an example for each slot.

2024-11-07 10:08 UTC, lazappi commented on R/Seurat.R
> +    if (reduction@assay.used == assay_name) {
I can't find a better way to get the assay used so probably have to use `@` here

2024-11-07 10:08 UTC, lazappi commented on R/Seurat.R
> +  for (graph_name in names(seurat_obj@graphs)) {
```suggestion
  for (graph_name in SeuratObject::Graphs(seurat_obj)) {
```

2024-11-07 10:08 UTC, lazappi commented on R/Seurat.R
> +    graph <- seurat_obj@graphs[[graph_name]]
```suggestion
    graph <- seurat_obj[[graph_name]]
```

2024-11-08 09:27 UTC, LouiseDck commented on R/Seurat.R
> +  }
Yes -- My comment was wrongly placed and you already solved part of it :tada:

2024-11-08 09:27 UTC, LouiseDck commented on R/Seurat.R
> +#' Each item in the list must be a named list with keys 'key', 'obsm', and 'varm'. See section "Reduction mapping" for
This seems wrong -- it also does not correspond to the "obsm mapping" section.

2024-11-09 08:06 UTC, rcannood commented on R/check_requires.R
> +          "{.code install.packages(c({missing_str}))}"
> These instructions won't work for Bioconductor packages.

Fixed!

> updating all messages/warning/errors to use {cli} if we are going to depend on it anyway?

I'd like that, but let's do this in a separate PR :sweat_smile:

2024-11-09 08:10 UTC, rcannood commented on R/Seurat.R
> +#' A named list to map AnnData `obsm` and `varm` to Seurat reductions. Each item in the list must be a named list
Tried to make the notations more consistent!

2024-11-09 08:25 UTC, rcannood commented on R/Seurat.R
> +    obj@assays[[assay_name]] <- SeuratObject::AddMetaData(
`GetAssayData` and `SetAssayData` returns the data of the assay, not the assay itself.

I can use `obj[[assay_name]]` instead of `obj@assays[[assay_name]]` but I don't see the added benefit. If anything, `obj[[assay_name]]`  allows me to accidentally interact with data that is not actually an assay.

Upon looking closer, I see that SeuratObject provides [documentation of the Seurat class](https://satijalab.github.io/seurat-object/reference/Seurat-class.html) for slots like `@assays`, `@graphs`, ..., so I'd say using these slots is actually ok.

2024-11-09 08:27 UTC, rcannood commented on R/Seurat.R
> +  obj@misc <- list()
Doesn't work as a replacement for this line of code.

```
SeuratObject::Misc(obj) <- list()
Error in `Misc<-.Seurat`(`*tmp*`, value = list()) : 
  argument "slot" is missing, with no default
```

In this case, we could **assume** that `obj@misc` is an empty list to begin with.

2024-11-09 08:40 UTC, rcannood commented on R/Seurat.R
> +#' Each item in the list must be a named list with keys 'key', 'obsm', and 'varm'. See section "Reduction mapping" for
Thanks for noticing, has been fixed!

2024-11-09 08:43 UTC, rcannood commented on R/Seurat.R
>  from_Seurat <- function(
It's possible to expose `ad$to_Seurat()` and not `to_Seurat(ad)`, but we'll need to expose `from_Seurat(obj)` as this functionality is otherwise not accessible. This is the status quo ^^

2024-11-09 08:46 UTC, rcannood commented on R/Seurat.R
> +    assay_name <- SeuratObject::DefaultAssay(seurat_obj)
This would bypass the `requiredNamespace("SeuratObject")` ^^

I'll make a note in the docs.

2024-11-09 08:46 UTC, rcannood commented on R/Seurat.R
> +  seurat_assay <- seurat_obj@assays[[assay_name]]
`GetAssayData()` returns the data layer of the assay, not the assay object itself.

2024-11-09 08:48 UTC, rcannood commented on R/Seurat.R
>    obs <- seurat_obj@meta.data
[`@meta.data`](https://satijalab.github.io/seurat-object/reference/Seurat-class.html) is a documented slot of the Seurat -- I like the more explicit nature of this notation.

2024-11-09 08:56 UTC, rcannood commented on R/Seurat.R
> +      adata$obsp[[obsp_name]] <- as(seurat_obj@graphs[[key2]], "sparseMatrix")
Then lets stick to using @graphs, as this is more explicit. I don't want strange errors to occur because a user accidentally provided the name of a DR as a graph name.

2024-11-09 09:00 UTC, rcannood commented on R/Seurat.R
> +  for (layer_name in names(seurat_assay@layers)) {
The code was used to use these functions where possible :)

2024-11-09 09:00 UTC, rcannood commented on R/Seurat.R
> +    reduction <- seurat_obj@reductions[[reduction_name]]
@reductions is kept as a safety precaution

2024-11-09 09:01 UTC, rcannood commented on R/Seurat.R
> +    graph <- seurat_obj@graphs[[graph_name]]
`@graphs` is kept as a precaution

2024-11-09 09:11 UTC, rcannood commented on R/Seurat.R
>    )
I changed it to:

```

  tryCatch(
    {
      generator$new(
        obs = obs,
        var = var,
        ...
      )
      # ... add more data ...
    },
    error = function(e) {
      if (output_class == "HDF5AnnData") {
        on.exit(cleanup_HDF5AnnData(...))
      }
      stop(e)
    }
  )
```

wdyt?

2024-11-09 09:35 UTC, rcannood commented
Phew. I think I addressed most of the comments. 

* Wherever SeuratObject had functions for accessing certain data, these functions were used (e.g. changed `names(obj@layers)` for `SeuratObject::Layers(obj)`). However, I didn't change code when the alternative was less specific (e.g. changing `obj@assays[[assay_name]]` for `obj[[assay_name]]`) or readable (e.g. changing `obj@meta.data` for `obj[[]]`) to avoid accidental bugs.
* Tried to clean up with `cleanup_HDF5AnnData` when an error occurs while converting to HDF5AnnData. @lazappi Can you take a look?
* Changing all `stop()`, `warning()`, `cat()`, etc.. to use **{cli}** sounds great, but let's do that in a separate PR

2024-11-12 07:07 UTC, lazappi approved these changes
I think I'm happy with this now

2024-11-12 07:07 UTC, lazappi commented on R/SingleCellExperiment.R
> +      }
Should this be outside the error part so the cleanup is still run if one of the later steps fails?

2024-11-12 09:37 UTC, rcannood commented on R/SingleCellExperiment.R
> +      }
I think there is no code after this call in the function. The SCE converter is simply a bit limited at this stage

2024-11-12 10:37 UTC, merged