Zarr support
scverse/anndataR pull request #190
Opened 2024-11-05 16:09 UTC by keller-mark

Fixes #91 

The main public-facing changes here are:
- The `ZarrAnnData` class
- `read_zarr` and `write_zarr` top-level functions
- Support for `from_Seurat(output_class="ZarrAnnData")`
- Support for `from_SingleCellExperiment(output_class="ZarrAnnData")`

Internally:
- `read_zarr_helpers.R` is the zarr analog of `read_h5ad_helpers.R`
- Test fixtures within `inst/extdata/example.zarr` (this makes the diff noisy, apologies)
- Lots of tests:
  - `test-Zarr-read.R` (35 new tests)
  - `test-Zarr-write.R` (70)
  - `test-ZarrAnnData.R` (26)
  - `test-h5ad-zarr.R` (17)
 
A number of these functions generate warnings in the R console that are intended to be followed up on to improve the code (and should probably be resolved as end users may not appreciate them), but the tests still pass despite these warnings.

2024-11-05 20:16 UTC, rcannood requested changes
Fantastic work @keller-mark and @Artur-man !

I went through the PR for a first time and left some minor comments. I will review the code by running it a couple of times next :)

2024-11-05 20:16 UTC, rcannood commented on R/read_zarr.R
> +  )
Should add HDF5AnnData as an option here as well. Which means that we should probably store this information elsewhere to avoid code duplication

```suggestion
read_zarr <- function(
    path,
    to = c("InMemoryAnnData", "HDF5AnnData", "SingleCellExperiment", "Seurat", "ZarrAnnData"),
    ...) {
  to <- match.arg(to)

  adata <- ZarrAnnData$new(path)

  fun <- switch(to,
    "SingleCellExperiment" = to_SingleCellExperiment,
    "Seurat" = to_Seurat,
    "InMemoryAnnData" = to_InMemoryAnnData,
    "HDF5AnnData" = to_HDF5AnnData,
    "ZarrAnnData" = NULL
  )

2024-11-05 20:16 UTC, rcannood commented on R/read_zarr_helpers.R
> +    path <- name
where are a lot of linting issues in this file -- could you run `lintr::lint_package()` and fix any issues that pop up?

2024-11-05 20:16 UTC, rcannood commented on inst/extdata/example2.zarr/.zgroup
This file should probably be removed

2024-11-06 09:31 UTC, Artur-man commented on inst/extdata/example2.zarr/.zgroup
done

2024-11-06 15:21 UTC, Artur-man commented on R/read_zarr_helpers.R
> +    path <- name
working on it now ...

2024-11-06 15:55 UTC, Artur-man commented
@rcannood @keller-mark should we add `pizzarr` only under `Suggests` in `DESCRIPTION` and no need to add a `Remotes` list here ? 

```
Suggests:
    ...
    ...
    pizzarr
Remotes:
    keller-mark/pizzarr
```

2024-11-06 16:12 UTC, Artur-man commented on R/read_zarr_helpers.R
> +    path <- name
done ... did a full `lint_package` check and corrected some R check issues too!

2024-11-06 16:13 UTC, Artur-man commented on R/read_zarr.R
> +  )
done ... mixed this with the latest commit! https://github.com/scverse/anndataR/pull/190/commits/d192e68ed312f212476a5490c973619f08e7c8de

2024-11-06 20:52 UTC, keller-mark commented
Good point, at minimum we should add a note to the Github README here https://github.com/scverse/anndataR/tree/main?tab=readme-ov-file#installation

2024-11-06 22:07 UTC, Artur-man commented
Ah, this is already added here, nevermind then only `Suggests` should work. 
https://github.com/keller-mark/anndataR/blob/d192e68ed312f212476a5490c973619f08e7c8de/R/ZarrAnnData.R#L240-L246

2024-11-07 06:47 UTC, lazappi commented
Not a proper review of the code but I wanted to raise that we plan to submit **{anndataR}** to Bioconductor (or maybe CRAN) at some point (hopefully soonish). This means we won't be able to depend on GitHub only packages. Do you have plans to submit **{pizzarr}** somewhere or could you rewrite this to use one of the public Zarr packages?

2024-11-07 08:19 UTC, Artur-man commented
@lazappi thanks for the notification, `pizzarr` could be submitted to CRAN soon. https://github.com/keller-mark/pizzarr/pull/93

2025-03-10 13:15 UTC, Artur-man commented
@keller-mark any opinions on this ? perhaps we can make Rarr/pizzarr optional with `options()` depending on the speed. 

Regardless it would be good to have zarr support for AnnDataR. We are currently using `reticulate`/`basilisk` env in `SpatialData` and causes problems already (too many dependancies, multiple env etc.). https://github.com/HelenaLC/SpatialData

That being said, any dependancy should either be in CRAN or BioC. If there are missing utilities in `Rarr` we can also contact the maintainer and/or send PRs there (I did some, which I can continue too).

2025-03-12 12:46 UTC, lazappi commented on inst/extdata/example.zarr/.zattrs
Can we please zip or something the example to make it a single file? I don't think we want to be tracking ~400 extra files in `git`. If we can avoid needing an example file that might be even better but I'm happy to keep it if it's bundled in some way.

2025-03-12 13:21 UTC, Artur-man commented on inst/extdata/example.zarr/.zattrs
should be easy to zip and unzip at tmpdir, will do

2025-03-14 09:49 UTC, Artur-man commented on inst/extdata/example.zarr/.zattrs
done

2025-04-12 20:33 UTC, Artur-man commented
I have quickly checked if `pizzarr` utilities could be replaced with https://github.com/grimbough/Rarr, unfortunately there exists a set of limitations to the BioC native package, which 
* for some basic utilities such as opening zarr stores and creating groups, had to come up with custom functions
* can't read/write boolean arrays yet 
* and throw errors when reading from some character arrays 
   - https://github.com/grimbough/Rarr/issues/20
   
Will be in touch to see if these are resolved in the future, otherwise no complete zarr function is both in CRAN/BioC and functionally complete yet.

2025-11-10 12:04 UTC, Artur-man commented
There is some progress in the Rarr package, would you guys like a clean PR (since there were so many updates since) or continuing here is fine ?

2025-11-11 06:22 UTC, lazappi commented
> There is some progress in the Rarr package, would you guys like a clean PR (since there were so many updates since) or continuing here is fine ?

Probably whatever is easiest for you and @keller-mark/whatever makes the PR easiest to understand. There have been a lot of changes to the package since this was opened so we would need to make sure those are included here.

I saw that **{Rarr}** is planning to have Zarr v3 support for the next release so I think that makes sense in terms of which backend package to use.

2025-11-13 19:40 UTC, Artur-man commented
I adapted the changes, was fairly easy. I will then continue here and refer back to Hugo if needed again.

2025-11-20 11:51 UTC, lazappi commented
I'm going to make this a draft for now, just to help with our organisation. Please let us know when it's ready to review.

2025-11-24 16:54 UTC, Artur-man commented
Guys, I am close .... I will add a new `example.zarr` here, however lets add a yml file to allow creating quick environments here, so the same files can be generated quickly later, and also ... would you like a separate `example_zarr.py` file ? 

https://github.com/scverse/anndataR/blob/5ffd79a05bbc4a99194b89a6432777cf2f1760a5/inst/scripts/example_h5ad.py#L1-L7

2025-11-25 07:18 UTC, lazappi commented
We tried to cover as many cases as possible in the example dataset so I would probably modify the script to also output a (tarred/zipped) Zarr as well as an H5AD (and maybe rename it to something like `create_example.py`) rather than creating a new one.

I noted down the versions just in case it became important later but maybe it makes sense to store them in a separate file. If you are regenerating the dataset I would probably also update the environment. I think there is also a version number in the script that should be bumped and a changelog that should be updated.

2025-12-04 08:52 UTC, lazappi commented
@Artur-man We have updated the CI. You will need to merge the `devel` branch here to get the new version.

2025-12-06 00:29 UTC, Artur-man commented
Some functions such as `read_h5ad_data_frame` and `read_h5ad_collection` would repeat themselves if we were to define a, e.g. `read_zarr_data_frame/_collection` since they do not directly call `rhdf5` or `Rarr` methods. 

I would instead open a new `read/write_file_helpers.R` to define these cross file format generic methods, and only keep file specific methods like `read_hdf5_numeric_scalar` where they are. 

If you want, I can implement them, otherwise we can explore after you review my changes. Up to you. I am still waiting for some changes in `Huber-group-EMBL/Rarr` but mostly we are ready.

2025-12-09 10:44 UTC, Bisaloo reviewed
FYI, the patterns I highlight here can also be detected via lintr if you use `all_linters()` and then selectively turn off the linters you don't want.

For example: https://github.com/Huber-group-EMBL/Rarr/blob/devel/.lintr

2025-12-09 10:44 UTC, Bisaloo commented on R/Rarr_utils.R
> +  split.name <- strsplit(name, split = "\\/")[[1]]
It'll be slightly faster if regexes are not used:

```suggestion
  split.name <- strsplit(name, split = "/", fixed = TRUE)[[1]]
```

2025-12-09 10:44 UTC, Bisaloo commented on R/Rarr_utils.R
> +    split.name <- vapply(seq_len(length(split.name)),
```suggestion
    split.name <- vapply(seq_along(split.name),
```

2025-12-09 10:44 UTC, Bisaloo commented on R/write_zarr_helpers.R
> +  }
If you're using a recent version of R:

```suggestion
  dims <- dim(value) %||% length(value)
```

(you can also redefine the operator in this pkg for compatibility with older R versions)

2025-12-09 19:42 UTC, Artur-man commented on R/write_zarr_helpers.R
> +  }
oh I will change this directly, anndataR requires 4.5 and later anyways. Thanks Hugo.

2025-12-09 19:42 UTC, Artur-man commented on R/Rarr_utils.R
> +    split.name <- vapply(seq_len(length(split.name)),
done

2025-12-09 19:43 UTC, Artur-man commented on R/Rarr_utils.R
> +  split.name <- strsplit(name, split = "\\/")[[1]]
done

2025-12-11 10:48 UTC, lazappi commented
> Some functions such as `read_h5ad_data_frame` and `read_h5ad_collection` would repeat themselves if we were to define a, e.g. `read_zarr_data_frame/_collection` since they do not directly call `rhdf5` or `Rarr` methods.

I think they are slightly different because one will call `read_h5ad_element()` and the other will call `read_zarr_element()`. I'm open to reducing redundancy where it makes sense and is still easy to follow but maybe it's better to leave for a separate PR so it's easier to review the Zarr functionality without other changes.

2025-12-11 11:01 UTC, Artur-man commented
Then @lazappi perhaps we can start your review, let me know if you guys want me to change anything (there are lots of changes!). Meanwhile, @Bisaloo will keep working on fixing a few small issues in `Rarr`.

2025-12-12 10:44 UTC, lazappi requested changes
We will probably need some more rounds of reviews but hopefully I've caught a lot of stuff already.

Additional comments:
- I commented on some style things the first time I saw them but please do the same wherever else it is relevant
- The documentation in `AnnData-usage` needs to be updated to add `ZarrAnnData`
- Round trip tests for Zarr need to be added
- We should probably show Zarr usage somewhere in a main vignette
- Please try to get the CI checks to pass

2025-12-12 10:44 UTC, lazappi commented on inst/scripts/example_files.py
> +# zip.close()
Maybe this should be uncommented?

2025-12-12 10:44 UTC, lazappi commented on inst/scripts/requirements.yml
If we are adding this we can probably remove the versions from the script.

2025-12-12 10:44 UTC, lazappi commented on R/AbstractAnnData.R
> +    #' Convert to an [`ZarrAnnData`]
```suggestion
    #' Convert to a [`ZarrAnnData`]
```

2025-12-12 10:44 UTC, lazappi commented on R/AbstractAnnData.R
> +    #' @return An [`ZarrAnnData`] object
```suggestion
    #' @return A [`ZarrAnnData`] object
```

2025-12-12 10:44 UTC, lazappi commented on R/AbstractAnnData.R
> +    #' Write the `AnnData` object to an H5AD file
```suggestion
    #' Write the `AnnData` object to a Zarr file
```

2025-12-12 10:44 UTC, lazappi commented on R/Rarr_utils.R
> +#' @export
These are internal functions that shouldn't be exported, use `@noRd` instead

2025-12-12 10:44 UTC, lazappi commented on R/Rarr_utils.R
> +#' @export
Please be more consistent with the formatting of the function documentation, something like:

```suggestion
#' Create Zarr group
#'
#' Create a new group in a Zarr store
#'
#' @param store the location of the Zarr store
#' @param name name of the group to create
#' @param version Zarr version
#'
#' @noRd
#'
#' @examples
#' store <- tempfile(fileext = ".zarr")
#' create_zarr(store)
#' create_zarr_group(store, "gp")
```

2025-12-12 10:44 UTC, lazappi commented on R/Rarr_utils.R
> +#' @importFrom utils tail
Imports from common packages can go in `anndataR-package.R`

2025-12-12 10:44 UTC, lazappi commented on R/Rarr_utils.R
> +  split.name <- strsplit(name, split = "/", fixed = TRUE)[[1]]
Use `snake_case` for variable names

2025-12-12 10:44 UTC, lazappi commented on R/Rarr_utils.R
> +      stop("Currently only zarr v2 is supported!")
Use `cli_abort()` for errors

2025-12-12 10:44 UTC, lazappi commented on R/Rarr_utils.R
> +    v3 = {
What are your thoughts on being able to support v3?

2025-12-12 10:44 UTC, lazappi commented on R/Rarr_utils.R
> +  switch(
Should this check be in `create_zarr()` (or wherever it will be first triggered)?

2025-12-12 10:44 UTC, lazappi commented on R/Rarr_utils.R
> +#' @return returns TRUE if zarr store is not empty
If the function is named `is_zarr_empty()` it should return `TRUE` when the store is empty. I'm not sure if it's the name or the documentation that is wrong but they don't match.

2025-12-12 10:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +        warning("No encoding found for element '", name, "'")
Use `cli_warn()` for warnings

2025-12-12 10:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +read_zarr_encoding <- function(store, name, stop_on_error = TRUE) {
The `stop_on_error` isn't needed here, please make it match the `read_h5ad_encoding()` function

2025-12-12 10:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +    if (is.null(encoding_list)) {
This check isn't needed because `read_zarr_encoding()` should fail if there is no encoding found

2025-12-12 10:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +  }
This probably isn't needed here

2025-12-12 10:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +  }
This may not be needed depending on what `Rarr::read_zarr_array()` returns

2025-12-12 10:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +  )
```suggestion
  purrr::map(field_names, function(.field) {
    as.vector(read_zarr_array(store, file.path(name, .field)))
  }) |>
    setNames(field_names)
```

2025-12-12 10:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +  )
Maybe this could use `read_zarr_collection()`?

2025-12-12 10:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +  data[data == "NA"] <- NA
I don't think `string_array` is nullable but we should check

2025-12-12 10:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +  }
I don't think this is needed as this can never be written

2025-12-12 10:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +  }
I don't think this is needed as the attribute should always be written

2025-12-12 10:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +#' is not provided in the output. In either case row names are not set.
This should have the same behaviour as `read_h5ad_data_frame()`. The index should always be read and set as the row names. I think the function is correct but the documentation needs updating.

2025-12-12 10:44 UTC, lazappi commented on R/write_zarr.R
> +#' Write an Zarr file
```suggestion
#' Write a Zarr file
```

2025-12-12 10:44 UTC, lazappi commented on R/write_zarr.R
> +#' written uncompressed.
Is this true for Zarr as well?

2025-12-12 10:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +    type,
Need to add a `read_zarr_null()` function

2025-12-12 10:44 UTC, lazappi commented on R/write_zarr_helpers.R
> +  write_fun <-
Need to add `write_zarr_null()`

2025-12-12 10:44 UTC, lazappi commented on R/write_zarr_helpers.R
> +  value[is.na(value)] <- "NA"
Don't think we need this

2025-12-12 10:44 UTC, lazappi commented on R/ZarrAnnData.R
> +      if (is.character(file)) {
I think for Zarr you only have a path, no handle object? If that is the case some of the logic here can be simplified.

2025-12-12 10:44 UTC, lazappi commented on R/ZarrAnnData.R
> +          "File {.file {file}} is not a valid Zarr file."
Maybe this (and similar messages/documentation) needs to say something like "AnnData Zarr file" because there is no AnnData-specific extension like there is for H5AD.

2025-12-12 10:44 UTC, lazappi commented on R/ZarrAnnData.R
> +    close = function() {},
This can be removed if it's not needed

2025-12-12 10:44 UTC, lazappi commented on R/ZarrAnnData.R
> +cleanup_ZarrAnnData <- function(...) {
I don't think this is used anywhere? It can be removed if so.

2025-12-12 10:44 UTC, lazappi commented on tests/testthat/test-h5ad-zarr.R
> +  skip("read_zarr_rec_array is not implemented yet")
I think this is implemented now?

2025-12-12 10:44 UTC, lazappi commented on tests/testthat/test-h5ad-zarr.R
> +test_that("reading dataframes works", {
```suggestion
test_that("reading dataframes is the same for h5ad and zarr", {
```

2025-12-12 10:44 UTC, lazappi commented on tests/testthat/test-h5ad-zarr.R
> +  skip("for now, example.zarr and example.h5ad are not identical!")
Why are they not identical?

2025-12-12 10:44 UTC, lazappi commented on tests/testthat/test-h5ad-zarr.R
> +test_that("reading H5AD as SingleCellExperiment is same for h5ad and zarr", {
Should probably add a test for Seurat

2025-12-12 10:44 UTC, lazappi commented on vignettes/articles/software_design.Rmd
> +- The `ZarrAnnData` provides an interface to a Zarr data (i.e. Zarr store) and, similar to a H5AD file, minimal data is stored in memory until it is requested by the user. It is as an intermediate ob
```suggestion
- The `ZarrAnnData` provides an interface to a Zarr store and, similar to a H5AD file, minimal data is stored in memory until it is requested by the user. It is as an intermediate object when reading/writing Zarr stores but can be useful for accessing parts of large files.
```

2025-12-12 11:14 UTC, Artur-man commented
> We will probably need some more rounds of reviews but hopefully I've caught a lot of stuff already.
> 
> Additional comments:
> 
> * I commented on some style things the first time I saw them but please do the same wherever else it is relevant
> * The documentation in `AnnData-usage` needs to be updated to add `ZarrAnnData`
> * Round trip tests for Zarr need to be added
> * We should probably show Zarr usage somewhere in a main vignette
> * Please try to get the CI checks to pass

awesome @lazappi I will get to it.

2025-12-12 11:27 UTC, Artur-man commented on R/read_zarr_helpers.R
> +  data[data == "NA"] <- NA
This we have discussed with @Bisaloo to how to implement. Currently, rhdf5 forces NAs to "NA" when saved as string arrays, and then return as NA back when returned from the `.h5`.

This doesnt happen in `Rarr`, so we imitate in `anndataR` instead. 

See more here: https://github.com/Huber-group-EMBL/Rarr/issues/86

2025-12-12 12:51 UTC, Bisaloo commented on inst/scripts/requirements.yml
I learned about this recently, which can be a good lightweight way to document versions without having to create a dedicated environment file: https://docs.astral.sh/uv/guides/scripts/#declaring-script-dependencies

Note that it's not uv-specific but it's also [documented in the official python docs](https://packaging.python.org/en/latest/specifications/inline-script-metadata/#inline-script-metadata).

2025-12-12 12:51 UTC, Bisaloo commented on R/read_zarr_helpers.R
> +  }
`Rarr::read_zarr_array()` currently always returns arrays (i.e., `dim()` is not `NULL`). I don't expect this to change as I like the idea of a consistent output class.

2025-12-12 12:51 UTC, Bisaloo commented on README.md
> +  [zarr](https://www.bioconductor.org/packages/release/bioc/html/Rarr.html):
```suggestion
  [Rarr](https://www.bioconductor.org/packages/release/bioc/html/Rarr.html):  
```

2025-12-12 12:57 UTC, Artur-man commented on R/Rarr_utils.R
> +    v3 = {
@Bisaloo is working on it, i think he wants to do this until march-april

2025-12-12 19:02 UTC, Artur-man commented on README.md
> +  [zarr](https://www.bioconductor.org/packages/release/bioc/html/Rarr.html):
fixed

2025-12-12 19:09 UTC, Artur-man commented on vignettes/articles/software_design.Rmd
> +- The `ZarrAnnData` provides an interface to a Zarr data (i.e. Zarr store) and, similar to a H5AD file, minimal data is stored in memory until it is requested by the user. It is as an intermediate ob
fixed

2025-12-12 19:10 UTC, Artur-man commented on tests/testthat/test-h5ad-zarr.R
> +  skip("for now, example.zarr and example.h5ad are not identical!")
some readers are not implemented yet, but will check again.
https://github.com/scverse/anndataR/pull/190#issuecomment-3619051125

2025-12-12 19:11 UTC, Artur-man commented on tests/testthat/test-h5ad-zarr.R
> +test_that("reading dataframes works", {
fixed

2025-12-12 20:20 UTC, Artur-man commented on tests/testthat/test-h5ad-zarr.R
> +  skip("read_zarr_rec_array is not implemented yet")
Hmm, ok the skip here is misleading, since `Rarr` currently doesn't read arbitrary structured data types, but my current implementation under `read_zarr_rec_array` only works for the example data. So it should stay like this until the following is fixed: 
https://github.com/Huber-group-EMBL/Rarr/issues/81

2025-12-12 20:21 UTC, Artur-man commented on R/AbstractAnnData.R
> +    #' Convert to an [`ZarrAnnData`]
fixed

2025-12-12 20:21 UTC, Artur-man commented on R/AbstractAnnData.R
> +    #' @return An [`ZarrAnnData`] object
fixed

2025-12-12 20:34 UTC, Artur-man commented on R/Rarr_utils.R
> +  switch(
Hmm, good idea but I think it doesn't matter where it is put. Either in `create_zarr` or `create_zarr_group` this check should be performed. Since root zarr is a zarr group too, we call `create_zarr_group` with `create_zarr`. 

However, I like how you think. This functions are auxiliary and will be deprecated once @Bisaloo implements it in `Rarr`.

2025-12-12 21:30 UTC, Artur-man commented on R/read_zarr_helpers.R
> +  )
lets leave this for now, because we are still waiting @Bisaloo to implement readers for structured data. 
https://github.com/Huber-group-EMBL/Rarr/issues/81

2025-12-21 16:08 UTC, Artur-man commented
Errors I am getting at lint and pkgdown GHAs look unrelated to the package: 

```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
    unable to load shared object '/home/runner/work/_temp/Library/Rhdf5lib/libs/Rhdf5lib.so':
    libsz.so.2: cannot open shared object file: No such file or directory
```

2025-12-21 17:41 UTC, Artur-man commented
@Bisaloo also the tests that are passing for macos, ubuntu and windows are failing for macos (intel) and ubuntu-bioc-release. I understand the error in release (for obvious reasons), but macos-15 I don't know. Any ideas ? 

```
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
   5.         └─base::array(metadata$fill_value, dim = lengths(index))
  ── Error ('test-Zarr-read.R:87:3'): reading numeric scalars works ──────────────
  Error in `array(metadata$fill_value, dim = lengths(index))`: 'dim' cannot be of length 0
  Backtrace:
      ▆
   1. └─anndataR:::read_zarr_numeric_scalar(store, "uns/IntScalar") at test-Zarr-read.R:87:3
   2.   └─anndataR:::read_zarr_array(store, name)
   3.     └─Rarr::read_zarr_array(file.path(store, name))
   4.       └─Rarr:::read_data(...)
   5.         └─base::array(metadata$fill_value, dim = lengths(index))
  
  [ FAIL 4 | WARN 447 | SKIP 12 | PASS 1842 ]
```

https://github.com/scverse/anndataR/actions/runs/20411185095/job/58648259569?pr=190

2025-12-21 17:47 UTC, Bisaloo commented
Yes, it looks that on this runner, Rarr 1.11.9 is installed, when support for reading scalars was added in Rarr 1.11.12. I think it's related to BioC devel not having more recent binaries for macOS x86 yet.

Maybe try setting:

```yaml
Imports:
    Rarr (>= 1.11.12)
```

In `DESCRIPTION` to force installation from source?

This will not work for the runner using BioC release but it's already failing anyways.

2025-12-21 18:05 UTC, Artur-man commented
I see. Then I will assume all checks are passing for now. thanks man

2025-12-21 18:48 UTC, Artur-man commented on R/Rarr_utils.R
> +#' @importFrom utils tail
fixed

2025-12-21 18:48 UTC, Artur-man commented on R/Rarr_utils.R
> +  split.name <- strsplit(name, split = "/", fixed = TRUE)[[1]]
ok, I think it is fixed.

2025-12-21 18:55 UTC, Artur-man commented on R/Rarr_utils.R
> +      stop("Currently only zarr v2 is supported!")
fixed

2025-12-21 18:58 UTC, Artur-man commented on R/Rarr_utils.R
> +#' @return returns TRUE if zarr store is not empty
fixed

2025-12-21 18:58 UTC, Artur-man commented on R/read_zarr_helpers.R
> +        warning("No encoding found for element '", name, "'")
fixed

2025-12-21 18:59 UTC, Artur-man commented on R/read_zarr_helpers.R
> +read_zarr_encoding <- function(store, name, stop_on_error = TRUE) {
fixed

2025-12-21 18:59 UTC, Artur-man commented on R/read_zarr_helpers.R
> +    if (is.null(encoding_list)) {
fixed

2025-12-21 19:01 UTC, Artur-man commented on R/read_zarr_helpers.R
> +  )
will leave until https://github.com/Huber-group-EMBL/Rarr/issues/81 is fixed.

2025-12-21 19:03 UTC, Artur-man commented on R/read_zarr_helpers.R
> +#' is not provided in the output. In either case row names are not set.
fixed

2025-12-21 19:03 UTC, Artur-man commented on R/read_zarr_helpers.R
> +  }
fixed

2025-12-21 19:03 UTC, Artur-man commented on R/read_zarr_helpers.R
> +  }
fixed

2025-12-21 19:05 UTC, Artur-man commented on R/write_zarr.R
> +#' Write an Zarr file
fixed

2025-12-21 19:15 UTC, Artur-man commented on R/write_zarr_helpers.R
> +  value[is.na(value)] <- "NA"
nope, unfortunately the behaviour is not the same as in rhdf5. @Bisaloo wanna comment ? 

```
> store <- tempfile(fileext = ".zarr")
> create_zarr(store = store)
> string <- LETTERS[1:5]
> string[5] <- NA
> write_zarr_element(string, store, "string_array")
NULL
Warning message:
Could not write element 'string_array' of type 'character': missing value where TRUE/FALSE needed 
```

2025-12-21 19:46 UTC, Artur-man commented on R/read_zarr_helpers.R
> +    type,
fixed, @lazappi are there tests for this for hdf5/h5ad ?

2025-12-21 19:47 UTC, Artur-man commented on R/write_zarr_helpers.R
> +  write_fun <-
need to check with @Bisaloo for this.

2025-12-21 19:48 UTC, Artur-man commented
Current issues: 

- [x] https://github.com/Huber-group-EMBL/Rarr/pull/82
- [x] https://github.com/Huber-group-EMBL/Rarr/issues/86
- [x] https://github.com/Huber-group-EMBL/Rarr/issues/81
- [x] implement `write_zarr_null`.
- [x] update `ZarrAnnData$initialize` since Zarr store doesn't have a handler.
- [x] The documentation in AnnData-usage needs to be updated to add ZarrAnnData
- [x] We should probably show Zarr usage somewhere in a main vignette
- [x] https://github.com/Huber-group-EMBL/Rarr/pull/104
- [x] Support for Unicode rec-arrays https://github.com/Huber-group-EMBL/Rarr/issues/81 
- [x] fix roundtrip tests for zarr
- [x] remove `eval=FALSE` from vignette chunks after fixes
- [x] Get the CI checks to pass

2025-12-21 20:01 UTC, Artur-man commented on R/ZarrAnnData.R
> +          "File {.file {file}} is not a valid Zarr file."
I see makes sense. Fixed

2025-12-21 20:05 UTC, Artur-man commented on tests/testthat/test-h5ad-zarr.R
> +test_that("reading H5AD as SingleCellExperiment is same for h5ad and zarr", {
fixed, but skipping for now until identical.

2025-12-22 08:28 UTC, Artur-man commented on inst/scripts/example_files.py
> +# zip.close()
done

2026-01-01 10:37 UTC, Artur-man commented on R/ZarrAnnData.R
> +    close = function() {},
fixed

2026-01-01 10:38 UTC, Artur-man commented on R/ZarrAnnData.R
> +cleanup_ZarrAnnData <- function(...) {
fixed

2026-01-01 10:55 UTC, Artur-man commented on R/ZarrAnnData.R
> +      if (is.character(file)) {
ok, I added some additional checks, thus now if `file` is not a character then it will give an error. But let me know I have missed something here. 

I also check if the file is a valid zarr folder, which is different than the folder being a valid anndata-zarr.

2026-01-08 15:15 UTC, Artur-man commented on R/write_zarr_helpers.R
> +  write_fun <-
the read and write of null encoding is strictly based on the `.zattrs`. I have tried reading the null array in a zarr v2 implementation and that gives an error. Thus, I will just write an empty logical array here with null encoding in the attr. I will leave a `TODO:` for future correction though.

2026-01-21 14:19 UTC, Artur-man commented on tests/testthat/test-h5ad-zarr.R
> +test_that("reading H5AD as SingleCellExperiment is same for h5ad and zarr", {
just letting you know, exact equality here is hard to achieve ... this is because of how structed data types (rec arrays are read between h5ad and zarr, and even between h5py and rhdf5):

see here
Huber-group-EMBL/rhdf5#192

2026-01-21 14:21 UTC, Artur-man commented on tests/testthat/test-h5ad-zarr.R
> +test_that("reading mappings is same for h5ad and zarr", {
There is a difference between rhdf5, Rarr and h5py on how rec arrays and structured data types are read. 

To me, h5py and Rarr reads it correctly, but rhdf5 does not:
Huber-group-EMBL/rhdf5#192

2026-01-21 14:35 UTC, Artur-man commented
We are really close, tests are passing on my local but we have to wait until changes in `Rarr` are in BioC-devel. 
Let me give a break I will review the entire PR. Please also let me know if you catch stuff, otherwise I will get back to this to finalize. 

Thanks @Bisaloo again for answering all issues of Rarr!

2026-01-22 09:22 UTC, lazappi commented on tests/testthat/test-h5ad-zarr.R
> +test_that("reading mappings is same for h5ad and zarr", {
Maybe we need an issue for this here as well? From our point of view it doesn't matter so much what is returned by **{rhdf5}** as long as what we return from the `AnnData` matches Python.

Going the other way (writing a `recarray`) is more difficult because we don't know when to use that format. I don't think we test this. Also, I don't think the `AnnData` disk spec really covers alternative arrays like `recarray`.

2026-01-26 13:04 UTC, Artur-man commented on tests/testthat/test-h5ad-zarr.R
> +test_that("reading mappings is same for h5ad and zarr", {
https://github.com/scverse/anndataR/issues/409

2026-01-27 19:38 UTC, Artur-man commented on tests/testthat/test-h5ad-zarr.R
> +  skip("for now, example.zarr and example.h5ad are not identical!")
should be done now

2026-01-27 19:38 UTC, Artur-man commented on tests/testthat/test-h5ad-zarr.R
> +test_that("reading H5AD as SingleCellExperiment is same for h5ad and zarr", {
mostly done, but also being addressed in https://github.com/scverse/anndataR/issues/409

2026-01-27 19:39 UTC, Artur-man commented on tests/testthat/test-h5ad-zarr.R
> +  skip("read_zarr_rec_array is not implemented yet")
done

2026-01-27 20:19 UTC, Bisaloo commented
As discussed in the bioconductor zulip, you're not likely to get up-to-date macOS x86 binaries for Rarr. So you'll need to either force installing from source, or add the bioc r-universe as an additional repository for this test to pass.

Alternatively, setting 1.11.24 as minimum required version for Rarr might do the trick to force installing from source when a recent enough binary isn't available.

2026-02-25 17:30 UTC, Artur-man commented on inst/scripts/requirements.yml
Hmm, I actually like this: 
https://docs.astral.sh/uv/guides/scripts/#declaring-script-dependencies

Let me know what you think @lazappi, I can embed it and drop yml ... but I do not know if this would make development harder for people used to running conda env through yml.

2026-02-25 17:35 UTC, Artur-man commented on R/Rarr_utils.R
> +  switch(
I would keep the check for zarr format here (until we can write zarr groups/arrays directly). Since zarr store is already a zarr root group and this check should be done for groups too. 

That being said, since we do not define higher-level classes for zarr stores (and instead open/create/modify groups and arrays directly via path), we cannot check if, for example, if the original zarr store is v3 or while the group you are trying to create is v2, which should normally throw an error. 

However, all these requires major changes to Rarr and its inner workings.

2026-02-25 17:36 UTC, Artur-man commented on R/Rarr_utils.R
> +    v3 = {
We can read zarr v3 now ... but not writing, perhaps this is enough for pushing zarr support to anndataR release.

2026-02-26 17:07 UTC, lazappi commented on inst/scripts/requirements.yml
Yeah, I think I prefer this to having a separate file as well

2026-02-26 17:10 UTC, lazappi commented on R/Rarr_utils.R
> +    v3 = {
Ok. I think the way this is set up is reasonable. The argument makes it clear we know there are versions and the message should be obvious that only v2 is currently supported. I would adjust the messages a bit but I will suggest something later.

2026-02-26 17:14 UTC, lazappi commented
> As discussed in the bioconductor zulip, you're not likely to get up-to-date macOS x86 binaries for Rarr. So you'll need to either force installing from source, or add the bioc r-universe as an additional repository for this test to pass.
> 
> Alternatively, setting 1.11.24 as minimum required version for Rarr might do the trick to force installing from source when a recent enough binary isn't available.

Could you please explain what the issue with this is? Is it something on the Bioconductor side so do we need to look into it?

I'm guessing the current release check is also expected to fail because we need a later version of **{Rarr}**?

2026-02-26 17:35 UTC, Bisaloo commented
> Could you please explain what the issue with this is? Is it something on the Bioconductor side so do we need to look into it?

BioC macOS x86 builder is no longer working. They're planning on pulling the binaries from r-universe, as they are doing with windows binaries, but it's still a work in progress.
In the meantime, the latest available version for macOS x86 binaries in BioC devel is quite outdated.
It's something that needs to be (and will be) resolved by Bioconductor.

But you can still work around the issue if you need to. By requiring installation from source (this should happen automatically if you request a version more recent than what the binaries provide). Or by getting the binaries from r-universe yourself.

> I'm guessing the current release check is also expected to fail because we need a later version of {Rarr}?

Yes, exactly

2026-03-12 16:39 UTC, rcannood reviewed
First round of comments prior to the hackathon!

Please merge devel again

2026-03-12 16:39 UTC, rcannood commented on inst/extdata/example_v2.zarr.zip
Can we Rbuildignore the example_v2.zarr.zip and example_v3.zarr.zip files?

2026-03-12 16:39 UTC, rcannood commented on inst/scripts/requirements.yml
> +      - leidenalg==0.11.0
```suggestion
      - leidenalg==0.11.0

```

Add missing newline

2026-03-12 16:39 UTC, rcannood commented on R/AbstractAnnData.R
> +        object = self,
fix linting issues

2026-03-12 16:39 UTC, rcannood commented on R/AbstractAnnData.R
> +      compression = c(
the compression arguments of `write_zarr` is different from `as_ZarrAnnData`. which one is correct?

2026-03-12 16:39 UTC, rcannood commented on R/read_h5ad_helpers.R
>    NULL
undo this unnecessary change to avoid merge conflicts

2026-03-12 16:39 UTC, rcannood commented on tests/testthat/test-roundtrip-empty-zarr.R
merge `test-roundtrip-*-zarr.R` into `test-roundtrip-*.R`

2026-03-12 16:39 UTC, rcannood commented on vignettes/articles/software_design.Rmd
> +* `r Biocpkg("Rarr")`: Read/write `*.zarr` stores natively
Rarr is a dependency, but is not a package related to reading or writing anndata files

2026-03-13 14:47 UTC, Artur-man commented on inst/extdata/example_v2.zarr.zip
what about example.h5ad ?

2026-03-13 14:52 UTC, Artur-man commented on R/AbstractAnnData.R
> +      compression = c(
are you talking about the possible values of `compression`. I think they are same already? 

```
as_ZarrAnnData <- function(
  # nolint end: object_name_linter
  adata,
  file,
  compression = c(
    "none",
    "gzip",
    "blosc",
    "zstd",
    "lzma",
    "bz2",
    "zlib",
    "lz4"
  ),
  mode = c("w-", "r", "r+", "a", "w", "x")
```

```
write_zarr <- function(
  object,
  path,
  compression = c(
    "none",
    "gzip",
    "blosc",
    "zstd",
    "lzma",
    "bz2",
    "zlib",
    "lz4"
  ),
  mode = c("w-", "r", "r+", "a", "w", "x"),
  ...

2026-03-13 15:02 UTC, Artur-man commented on vignettes/articles/software_design.Rmd
> +* `r Biocpkg("Rarr")`: Read/write `*.zarr` stores natively
Hmm, ok you are right, so delete then ? I cannot think of an implementation to be inspired from based on `Rarr`.

2026-03-13 15:03 UTC, Artur-man commented on R/read_h5ad_helpers.R
>    NULL
done

2026-03-13 15:04 UTC, Artur-man commented on inst/scripts/requirements.yml
> +      - leidenalg==0.11.0
done

2026-04-14 14:44 UTC, lazappi reviewed
A lot of these are TODOs for me 😸

2026-04-14 14:44 UTC, lazappi commented on inst/extdata/example_v2.zarr.zip
We use these in the examples/tests so they need to be in the package

2026-04-14 14:44 UTC, lazappi commented on inst/scripts/example_files.py
> +    shutil.rmtree(zarr_dir)
Can this be simplified?

2026-04-14 14:44 UTC, lazappi commented on R/AbstractAnnData.R
> +      compression = c(
This should be fixed now

2026-04-14 14:44 UTC, lazappi commented on R/Rarr_utils.R
> +#' @param version zarr version
Parameter descriptions should use sentence case e.g. `@param param Param does this`

2026-04-14 14:44 UTC, lazappi commented on R/Rarr_utils.R
> +#' create_zarr_group(store, "gp")
Don't need examples on unexported functions

2026-04-14 14:44 UTC, lazappi commented on R/Rarr_utils.R
> +  dir.create(file.path(store, split_name[1]), showWarnings = FALSE)
Add comments explaining this

2026-04-14 14:44 UTC, lazappi commented on R/Rarr_utils.R
> +    v3 = {
I think we should delay adding v3 write support to a future PR (when all the required functionality is available)

2026-04-14 14:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +  )))
Fix identation

2026-04-14 14:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +  }
Change to how this is done for H5AD. Could move to a function.

2026-04-14 14:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +  items <- items[!items %in% c(".zgroup", ".zattrs", ".zarray")]
Maybe we should store the metadata file vector somewhere and reuse it?

2026-04-14 14:44 UTC, lazappi commented on R/read_zarr_helpers.R
> +  items <- H5_ITER_INC_ORDERING(items)
Why is this needed?

2026-04-14 14:44 UTC, lazappi commented on R/write_zarr_helpers.R
> +  write_fun <-
We should check this matches whatever Python does

2026-04-14 14:44 UTC, lazappi commented on R/write_zarr_helpers.R
> +  value[is.na(value)] <- "NA"
The main thing is not that our Zarr and H5AD backends are the same but that they are both consistent with their matching Python implementations

2026-04-14 14:44 UTC, lazappi commented on R/write_zarr_helpers.R
> +}
Document this, use a better variable name

2026-04-14 14:44 UTC, lazappi commented on R/ZarrAnnData.R
> +#' @return An `ZarrAnnData` object
Use "A `ZarrAnnData`" not "An `ZarrAnnData`"

```suggestion
#' @return A `ZarrAnnData` object
```

2026-04-14 14:44 UTC, lazappi commented on R/ZarrAnnData.R
> +            "The Zarr file does not exist, or not a zarr file/store!"
```suggestion
            "The Zarr path does not exist or is not a valid Zarr store"
```

2026-04-14 14:44 UTC, lazappi commented on tests/testthat/test-h5ad-zarr.R
Restructure this to use a similar approach as the roundtrip tests

2026-04-14 14:44 UTC, lazappi commented on tests/testthat/test-Zarrv3-read.R
Merge this into `test-Zarr-read.R`

2026-04-14 14:44 UTC, lazappi commented on vignettes/articles/software_design.Rmd
> +* In-memory (`InMemoryAnnData`), HDF5-backed (`HDF5AnnData`), Zarr-backed (`ZarrAnnData`), Python-backed (`ReticulateAnnData`) back ends with a consistent interface
```suggestion
* In-memory (`InMemoryAnnData`), HDF5-backed (`HDF5AnnData`), Zarr-backed (`ZarrAnnData`) and Python-backed (`ReticulateAnnData`) back ends with a consistent interface
```

2026-04-14 14:44 UTC, lazappi commented on vignettes/anndataR.Rmd
> +  In contrast, `r Biocpkg("anndataR")` provides a native R H5AD and Zarr interface, removing the need for Python dependencies.
```suggestion
- `r Biocpkg("zellkonverter")` provides conversion of `SingleCellExperiment` objects to/from `AnnData` and reading/writing of `.h5ad`.
  This is facilitated via `r CRANpkg("reticulate")` using `r Biocpkg("basilisk")` to manage Python environments (native reading of `.h5ad` is also possible).
  In contrast, `r Biocpkg("anndataR")` provides a native R H5AD and Zarr interface, removing the need for Python dependencies.
```

2026-04-14 14:44 UTC, lazappi commented on vignettes/anndataR.Rmd
> +
These examples should be evaluated

2026-04-14 14:44 UTC, lazappi commented on vignettes/anndataR.Rmd
> +
Should be evaluated

2026-04-14 14:44 UTC, lazappi commented on vignettes/usage_seurat.Rmd
> +```
Evaluate examples

2026-04-14 14:44 UTC, lazappi commented on vignettes/usage_singlecellexperiment.Rmd
> +```
Evaluate examples

2026-04-14 14:48 UTC, Bisaloo commented on inst/scripts/example_files.py
> +    shutil.rmtree(zarr_dir)
FYI, I'm planning to write a separate, more full-featured, package to handle Zarr stores after the next Bioconductor release and it'll handle zip stores out of the box, which could make you life a bit easier here.

2026-04-15 08:47 UTC, lazappi commented on R/write_zarr_helpers.R
> +  value[is.na(value)] <- "NA"
I think this behaviour might actually be incorrect for H5AD, I've created an issue to follow up https://github.com/scverse/anndataR/issues/444

2026-04-17 14:18 UTC, Artur-man commented
@lazappi I think I did not check before finishing the hackathon. Do you set the default zarr version for write methods now ? or do you write only zarr v2 or v3 ? 

Again here is the parameter from `anndata` to set the default behaviour:
https://github.com/keller-mark/anndataR/blob/528eff0024f73b39c5147d5eb15e7ad8b9b7bade/inst/scripts/example_files.py#L142

would be nice to do that too if we are not rushing bioc release.

2026-04-19 06:29 UTC, Artur-man commented
Ok I took another look at it. The roundtrip tests and write tests do not have zarr v3 tests but thats fine for now I think. What is more important is that we can read both versions. Since this is gonna stay as the devel branch for another 6 months I can throw another PR later. Lets not overdo it. 

**UPDATE**: I wrote a version of `test-Zarr-write.R` loops over both v2 and v3 ... looks like its working.

2026-04-20 06:25 UTC, lazappi commented
I thought there was something that was missing from **{Rarr}** that was blocking writing v3 but I forgot to open an issue and come back to it. If you think the extra tests are passing do you want to push them here?

2026-04-23 15:40 UTC, lazappi commented
@keller-mark @Artur-man @Bisaloo 

Thanks for your contributions to this PR so far! To properly recognise them feel free to add yourselves as contributors to the `DESCRIPTION`. Or if it's easier comment with your details and I will add you.

2026-04-24 09:46 UTC, Bisaloo commented on DESCRIPTION
> +           comment = c(ORCID = "0000-0002-0441-9517", github = "Artur-man")),
```suggestion
           comment = c(ORCID = "0000-0002-0441-9517", github = "Artur-man")),
    person("Hugo", "Gruson", role = "ctb",
           comment = c(ORCID = "0000-0002-4094-1476", github = "Bisaloo")),
```

Thanks for the offer!

2026-04-24 13:39 UTC, rcannood approved these changes
LGTM!

2026-04-24 13:40 UTC, rcannood commented
Looks good, thank you all!

The CI is failing, but that's because of the Rarr minimal version requirement. When Bioconductor 3.23 is released, this issue should be fixed.

2026-04-24 13:40 UTC, merged

2026-04-24 13:45 UTC, Artur-man commented
We did it!!!  1.5 years ... thanks for everyone for the support @keller-mark @Bisaloo @rcannood @lazappi @LouiseDck

2026-04-24 16:04 UTC, ilan-gold commented
Congrats all!