Compare writing h5ad in Python & in R with h5diff
scverse/anndataR pull request #207
Opened 2024-12-05 10:48 UTC by LouiseDck

Tests the writing of various anndata slots. Compares what gets written in Python with what gets written in R.

2024-12-19 19:19 UTC, rcannood requested changes
Love the PR! Just needs a little bit of styling, I'm afraid!

2024-12-19 19:19 UTC, rcannood commented on tests/testthat/helper-py-R-equivalences.R
> +# does not test numeric_dense, numeric_dense_with_nas or integer_dense
Could you elaborate why not?

2024-12-19 19:19 UTC, rcannood commented on tests/testthat/test-roundtrip-obsmvarm.R
> +    test_that(paste0("Comparing a python generated .h5ad with obsm and varm '", name,
Why do you use nolint start here?

Please reformat :bow: You can use `styler::style_pkg()` if you like

```suggestion
  for (r_name in r_datatypes) {
    test_that(paste0("Comparing a python generated .h5ad with obsm and varm '", name,

2024-12-19 19:59 UTC, LouiseDck commented on tests/testthat/helper-py-R-equivalences.R
> +# does not test numeric_dense, numeric_dense_with_nas or integer_dense
Because of issue #198 
It might be better to just document this in the known_issues.yaml though

2025-01-16 21:14 UTC, rcannood commented on .github/workflows/R-CMD-check.yaml
> +
```suggestion
```

2025-01-16 21:22 UTC, rcannood approved these changes
LGTM! Go Louise :muscle:

2025-01-17 07:35 UTC, merged