Update example dataset
scverse/anndataR pull request #74
Opened 2023-05-08 13:11 UTC by lazappi

The example Krumsiek H5AD files from **{zellkonverter}** we were using for testing were missing some things we want to check. This dataset should be more complete and easier to add things to as needed.

2023-05-08 13:36 UTC, lazappi commented
Possibly we also want a similar R example (maybe using the in-memory interface)? I wasn't sure how best to do that but if we come up with something it could go here or in a separate PR.

2023-05-08 14:02 UTC, rcannood requested changes
Makes sense to remove the krumsiek dataset.

However, the resulting `example.h5ad` is too big for my liking. Can you create something that's a little smaller, e.g. <100KB?

2023-05-09 07:29 UTC, lazappi commented
Maybe??? It's only 100 cells x 200 genes so I'm not sure that can be reduced much. Some of the things might be redundant (in that they are the same types) but I'm not sure exactly which parts are taking up space. Any idea if there is an easy way to tell that from a HDF5 file?

I guess the other option would be to put it on Figshare and use **{BiocCache}** to get it as needed but it would be simpler to have something in the package.

2023-05-09 07:57 UTC, lazappi commented
Ok, I got it down to ~400kb. Small enough?

2023-05-10 07:12 UTC, rcannood approved these changes
400KB is already a lot better :)

2023-05-11 09:07 UTC, lazappi commented
FYI I want to add some things to this so please don't merge yet

2023-05-15 06:44 UTC, rcannood commented on R/HDF5-read.R
> -  requireNamespace("rhdf5")
Isn't it better to keep `requireNamespace("rhdf5")` in here, if these functions are meant to be transferred to a separate package?

This applies to all of the other `read_h5ad_*` and `write_h5ad_*` functions as well.

2023-05-15 06:44 UTC, rcannood commented on R/HDF5-read.R
> +#' A "record array" (recarray) is a Python NumPy array type that countains
Fix typo

```suggestion
#' A "record array" (recarray) is a Python NumPy array type that contains

2023-05-15 07:27 UTC, lazappi commented on R/HDF5-read.R
> -  requireNamespace("rhdf5")
I'm not quite sure what you mean? These functions aren't exported so I was imagining anyone depending on this would use `HDF5AnnData` which now contains a dependency check when the object is created. Maybe I'm missing something thought.

2023-05-15 07:33 UTC, rcannood commented on R/HDF5-read.R
> -  requireNamespace("rhdf5")
Weren't you planning on moving all of the `read_h5ad_*` and so on functions into a separate package which could then be used by anndataR, mudata and spatialdataR?

2023-05-15 07:44 UTC, lazappi commented on R/HDF5-read.R
> -  requireNamespace("rhdf5")
Ah, possibly... I had forgotten about that. Even if that does happen I think this would need to be revisited anyway. That package might just `import` **{rhdf5}** so this wouldn't be necessary there either.

2023-05-15 11:58 UTC, rcannood approved these changes
LGTM! (again)

2023-05-15 14:46 UTC, merged