Add H5AD read/write helpers
scverse/anndataR pull request #88
Opened 2023-07-06 14:50 UTC by lazappi

Add user functions for reading/writing H5AD files to/from `SingleCellExperiment`/`Seurat` objects. This will likely be the main interface for most normal users.

Also adds functions for creating dummy data objects (based on the `dummy_data()` test helper).

2023-07-11 09:23 UTC, lazappi commented
@rcannood The CI here (and on other PRs) is failing on all platforms with an error that I think is coming from your **{anndata}** package (in the round-trip tests). I can't replicate it locally, though to work out what is going on. Any thoughts on how you want to handle this?

2023-07-20 01:33 UTC, rcannood commented
Sigh! That issue has been popping up everywhere. It's because scipy 1.11 introduced some breaking changes. The development version of reticulate (at rstudio/reticulate) has resolved the issue, but the changes still need to be released on CRAN. I'll add a workaround to the repo for now.

2023-07-21 04:54 UTC, rcannood commented
@lazappi The main branch contains a workaround by switching to the development version of reticulate for now. Can you merge the main branch into this branch?

2023-08-07 10:19 UTC, rcannood requested changes
These changes make sense to me, though I'd like to allow users to also return hdf5anndata objects instead of only Seurat or SCE. Is this ok with you?

2023-08-07 10:19 UTC, rcannood commented on R/HDF5-write.R
> +  if (is(object, "SingleCellExperiment")) {
```suggestion
  if (inherits(object, "SingleCellExperiment")) {
```

2023-08-07 10:19 UTC, rcannood commented on R/HDF5-read.R
> +}
Can we make this function return an HDF5AnnData and an InMemoryAnnData as well?

```suggestion
read_h5ad <- function(path, to = c("HDF5AnnData", "InMemoryAnnData", "SingleCellExperiment", "Seurat")) {
  to <- match.arg(to)

  adata <- HDF5AnnData$new(path)

  switch(to,
    "SingleCellExperiment" = to_SingleCellExperiment(adata),
    "Seurat" = to_Seurat(adata),
    "HDF5AnnData" = adata,
    "InMemoryAnnData" = to_InMemory(adata)
  )
}
```

2023-08-07 10:19 UTC, rcannood commented on R/HDF5-write.R
> +  } else if (is(object, "Seurat")) {
```suggestion
  } else if (inherits(object, "Seurat")) {
```

2023-08-07 10:19 UTC, rcannood commented on R/anndataR-package.R
> +#' @importFrom methods as is
```suggestion
#' @importFrom methods as
```

2023-08-07 10:19 UTC, rcannood commented on R/HDF5-write.R
> +  } else {
also allow writing object which inherit `AbstractAnnData`

```suggestion
  } else if (inherits(object, "AbstractAnnData")) {
    to_HDF5AnnData(object, path) # todo: implement
  }

2023-08-08 06:18 UTC, lazappi commented
> These changes make sense to me, though I'd like to allow users to also return hdf5anndata objects instead of only Seurat or SCE. Is this ok with you?

I would prefer not to do this. Part of the reason for having these wrapper functions is to hide the `HDF5AnnData` interface object from most users. I can't see many use cases for interacting with it directly and I feel like anybody "advanced" enough to want to use it should be able to create the objects manually.

2023-08-28 06:54 UTC, rcannood commented
Personally, I see no downsides to enabling this functionality, and again it's something that I actually need in order to use the package myself. Sure, I could do it the roundabout way without using `read_h5ad`, but I don't know why this should be the case when we might as well just add this functionality.

However, I can agree to not making the default. Would this be okay with you?

2023-08-29 07:15 UTC, lazappi commented
I guess I can be convinced but I would maybe want to see what other people think. I think we just have a different philosophy/use case in mind. I know you have a use for it and could use it safely but you aren't a normal user and I worry about the average person misusing the interface objects if it's too easy to create them. Maybe I'm just paranoid though.

2023-08-31 10:18 UTC, rcannood commented
I merged some changes into this PR.

@lazappi Do you have an idea why the devel branch fails when reading the obs in certain unit tests?

2023-08-31 12:50 UTC, rcannood commented
Namely:

```
 ── Error ('test-HDF5-read.R:127:3'): reading H5AD as Seurat works ─────────���────
<subscriptOutOfBoundsError/error/condition>
Error in `element[["mask"]]`: subscript out of bounds
Backtrace:
    ▆
 1. ├─anndataR::read_h5ad(file, to = "Seurat") at test-HDF5-read.R:127:2
 2. │ └─anndataR::to_Seurat(adata) at anndataR/R/HDF5-read.R:452:2
 3. │   └─base::ncol(obj$obs) at anndataR/R/Seurat.R:42:2
 4. └─anndataR (local) `<fn>`() at anndataR/R/Seurat.R:42:2
 5.   └─anndataR:::read_h5ad_element(private$.h5obj, "/obs", include_index = FALSE) at anndataR/R/HDF5AnnData.R:43:8
 6.     └─anndataR (local) read_fun(file = file, name = name, version = version, ...) at anndataR/R/HDF5-read.R:67:2
 7.       └─anndataR:::read_h5ad_collection(file, name, column_order) at anndataR/R/HDF5-read.R:361:2
 8.         └─anndataR:::read_h5ad_element(...) at anndataR/R/HDF5-read.R:416:4
 9.           └─anndataR (local) read_fun(file = file, name = name, version = version, ...) at anndataR/R/HDF5-read.R:67:2
── Error ('test-HDF5AnnData.R:32:3'): reading obs works ────────────────────────
<subscriptOutOfBoundsError/error/condition>
Error in `element[["mask"]]`: subscript out of bounds
Backtrace:
    ▆
 1. └─anndataR (local) `<fn>`() at test-HDF5AnnData.R:32:2
 2.   └─anndataR:::read_h5ad_element(private$.h5obj, "/obs", include_index = FALSE) at anndataR/R/HDF5AnnData.R:43:8
 3.     └─anndataR (local) read_fun(file = file, name = name, version = version, ...) at anndataR/R/HDF5-read.R:67:2
 4.       └─anndataR:::read_h5ad_collection(file, name, column_order) at anndataR/R/HDF5-read.R:361:2
 5.         └─anndataR:::read_h5ad_element(...) at anndataR/R/HDF5-read.R:416:4
 6.           └─anndataR (local) read_fun(file = file, name = name, version = version, ...) at anndataR/R/HDF5-read.R:67:2

2023-09-01 06:14 UTC, lazappi commented
I think this might have to do with the changes to **{rhdf5}**. The nullable arrays are now read natively and you don't have to mess around with the masks yourself. I've fixed this in **{zellkonverter}** already so I can port that other here if you like.

2023-09-01 06:21 UTC, rcannood commented
I see! Is this related to #83 ?

2023-09-01 07:12 UTC, lazappi commented
Yes. Although I'm not sure if we are testing against the release or devel versions of Bioconductor packages (this change is only in devel).

2023-09-01 07:40 UTC, rcannood commented
The devel R CMD check uses the upcoming release of R, so it probably also has to use the development version of Bioconductor.

I created a PR (#90) which merges the changes into #83 into #88, which seems to have solved the issue. @lazappi Is it ok to merge #90?

2023-09-01 08:30 UTC, lazappi commented
I made one minor comment but otherwise yes.

2023-09-02 02:24 UTC, rcannood approved these changes

2023-09-02 02:25 UTC, rcannood commented
Thanks! #90 was merged. Can this PR also be merged?

2023-09-04 06:37 UTC, lazappi commented
Yeah, I think so

2023-09-04 07:57 UTC, merged